<?php include('config.php'); 
$var="Hi";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="this";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="is";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="chaitanya";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="and";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="i";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="am";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="studying";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="in";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="VIT";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="vellore.I";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=2 WHERE `string`='am';";
mysqli_query($con,$query);
$var="doing";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="my";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Btech";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=2 WHERE `string`='in';";
mysqli_query($con,$query);
$var="CSE.";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Chaitanya";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="took";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="admission";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=1 WHERE `string`='in';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=1 WHERE `string`='VIT';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `string`='in';";
mysqli_query($con,$query);
$var="2017.";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `string`='VIT';";
mysqli_query($con,$query);
$var="gives";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="ampfull";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="of";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="opporunities";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="to";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="achieve";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="success.";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='VIT';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='is';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='my';";
mysqli_query($con,$query);
$var="goal";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='to';";
mysqli_query($con,$query);
$var="procced";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='in';";
mysqli_query($con,$query);
$var="future.";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `string`='VIT';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `string`='is';";
mysqli_query($con,$query);
$var="ranked";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="17th";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `string`='in';";
mysqli_query($con,$query);
$var="2017";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="MHRD";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="rankings.";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="This";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="makes";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `string`='chaitanya';";
mysqli_query($con,$query);
$var="fell";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="proud.";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
header("Location:display.php");?>